version: '3.8'
services:
  server:
    image: golang:latest
    container_name: backend_golang
    environment:
      - POSTGRES_DB=musicshop
      - POSTGRES_USER=thanhliem
      - POSTGRES_PASSWORD=liem1234
      - DATABASE_HOST=postgres
      - DATABASE_PORT=41234:5432
    tty: true
    build: .
    ports:
      - 6868:6868
#    restart: on-failure
#    volumes:
#      - .:/server
#    depends_on:
#      - db
#    networks:
#      - learning

#  postgres:
#    image: postgres:latest
#    container_name: postgres_db
#    environment:
#      - POSTGRES_DB=musicshop
#      - POSTGRES_USER=thanhliem
#      - POSTGRES_PASSWORD=liem1234
#    ports:
#      - 41234:5432
