version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

#  server:
#    image: postgres:latest
#    container_name: backend_golang
#    build: .
#    env_file:
#      - .env
#    ports:
#      - "6868:6868"
#    volumes:
#      - .:/server