version: '3.8'

services:
  server:
    image: golang_musicshop
    container_name: backend_golang
    build: .
    ports:
      - "6868:6868"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
